import Navigation from "@/app/_components/Navigation";
import Logo from "@/app/_components/Logo";

import {Josefin_Sans} from "next/font/google"

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap"
})

import "@/app/_styles/globals.css"
import Header from "@/app/_components/Header";
import {ReservationProvider} from "@/app/_components/ReservationContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={`${josefin.className} bg-primary-950 text-gray-50 min-h-screen flex flex-col relative`}>
    <Header/>
    <div className="flex-1 px-8 py-12 grid">
      <ReservationProvider>
        <main className="max-w-7xl mx-auto w-full">{children}</main>
      </ReservationProvider>
    </div>
    </body>
    </html>
  )
}
